-- GAON-N 58 Integrated Portfolio Items (Bus, Shelter, Taxi, Rear, Video)
TRUNCATE TABLE `portfolio`;
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (1, 'bus', '광주 동신대한방병원 시내버스 내부 광고', '동신대한방병원', '광주 전역 시내버스 노선', '시내버스 내부 부착', '동신대한방병원 진료 안내 및 브랜드 홍보 시내버스 내부 광고 집행', '/images/port/port_01_1.jpg', '["/images/port/port_01_1.jpg"]', 1, 1, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (2, 'shelter', 'OK운전면허학원 남구 정류소 쉘터 광고', 'OK운전면허학원', '광주 남구 버스정류소', '승강장 쉘터 1개소', '운전면허 취득 타깃 유동인구 밀집 남구 정류소 조명 쉘터 광고 집행', '/images/port/port_02_1.jpg', '["/images/port/port_02_1.jpg"]', 1, 2, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (3, 'bus', '광주결혼협동조합 시내버스 후면 래핑 광고', '광주결혼협동조합', '광주 시내버스 간선노선', '시내버스 3대 (후면)', '후속 운전자 시선 집중 교차로 정체 구간 노출 버스 후면 광고', '/images/port/port_03_1.jpg', '["/images/port/port_03_1.jpg"]', 1, 3, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (4, 'shelter', '광산구 보건소 공공보건 버스승강장 와이드 쉘터 광고', '광산구 보건소', '광주 광산구 전역 버스승강장', '승강장 51개소 대형 집행', '광산구민 건강증진 및 보건사업 홍보 광산구 51개 거점 승강장 집중 송출', '/images/port/port_04_1.jpg', '["/images/port/port_04_1.jpg"]', 1, 4, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (5, 'shelter', '광산 센트럴 버스승강장 와이드 쉘터 광고', '광산 센트럴', '광주 남구 주요 승강장', '남구 거점 승강장', '남구 유동인구 밀집 구간 분양/입주 안내 정류소 조명 쉘터 광고', '/images/port/port_05_1.jpg', '["/images/port/port_05_1.jpg"]', 1, 5, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (6, 'bus', '광주소프트웨어마이스터고 신입생 모집 버스후면 광고', '광주마이스터고', '광주 주요 학원가 경유 노선', '시내버스 1대 (후면)', '학부모 및 중·고등학생 타깃 신입생 모집 버스 후면 임팩트 래핑', '/images/port/port_06_1.jpg', '["/images/port/port_06_1.jpg"]', 1, 6, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (7, 'bus', '광주광역시청 시정홍보 시내버스 인도면·하차문 광고', '광주광역시청', '광주 주요 간선/지선 3개 노선', '시내버스 3대 (옆면+하차문)', '광주광역시 핵심 시정 과제 홍보 버스 승하차 승객 및 보행자 타깃 집행', '/images/port/port_07_1.jpg', '["/images/port/port_07_1.jpg"]', 1, 7, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (8, 'bus', '광주안과 시내버스 승객용 좌석 시트커버 광고', '광주안과', '광주 시내버스 34대 전 노선', '시내버스 34대 (시트 전석)', '탑승 승객 평균 20분 이상 장시간 밀착 노출 시트커버 포스터', '/images/port/port_08_1.jpg', '["/images/port/port_08_1.jpg"]', 1, 8, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (9, 'bus', '광주광역치매센터 시내버스 3면 풀패키지 래핑 광고', '광주광역치매센터', '광주 전역 순환/간선 노선', '후면 + 빛고을면 + 하차문', '치매안심도시 광주 공공캠페인 후면/빛고을면/하차문 3방향 동시 노출 패키지', '/images/port/port_09_1.jpg', '["/images/port/port_09_1.jpg","/images/port/port_09_2.jpg"]', 1, 9, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (10, 'shelter', '한국폴리텍대학 광주캠퍼스 신입생 모집 승강장 광고', '한국폴리텍대학 광주캠퍼스', '광주 광산구 거점 정류소 8개소', '승강장 8곳', '취업 명문 폴리텍대학 학위/직업훈련과정 모집 광산구 주요 정류소 집행', '/images/port/port_10_1.jpg', '["/images/port/port_10_1.jpg"]', 1, 10, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (11, 'shelter', '광주금연지원센터 공공캠페인 남구 버스승강장 쉘터', '광주금연지원센터', '광주 남구 승강장 4개소', '승강장 4곳', '시민 건강증진 무료 금연치료 지원 홍보 남구 중심가 쉘터 집행', '/images/port/port_11_1.jpg', '["/images/port/port_11_1.jpg"]', 1, 11, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (12, 'shelter', '김대중컨벤션센터(DJ센터) 전시 박람회 승강장 쉘터 광고', '김대중컨벤션센터', '광주 광산구 주요 환승 정류소', '광산구 주요 승강장', '호남 최대 전시컨벤션 캠핑&로봇 박람회 관람객 유치 와이드 쉘터 광고', '/images/port/port_12_1.jpg', '["/images/port/port_12_1.jpg","/images/port/port_12_2.jpg"]', 1, 12, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (13, 'bus', '나주시티투어 시내버스 후면 임팩트 래핑 광고', '나주시', '광주-나주 광역 광역버스', '광역버스 후면', '나주 관광 명소 안내 및 축제 홍보 광주-나주 이동 차량 타깃 후면 광고', '/images/port/port_13_1.jpg', '["/images/port/port_13_1.jpg"]', 1, 13, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (14, 'bus', '남구정신건강복지센터 마음건강 시내버스 시트커버 광고', '남구정신건강복지센터', '광주 남구 경유 시내버스', '시내버스 20대 (시트커버)', '마음건강 상담전화 및 힐링 프로젝트 홍보 승객 눈높이 시트커버 부착', '/images/port/port_14_1.jpg', '["/images/port/port_14_1.jpg"]', 1, 14, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (15, 'bus', '광주 남구푸드존 시내버스 인도면 와이드 래핑 광고', '남구푸드존', '광주 남구 주요 간선버스', '시내버스 2대 (인도면)', '남구 먹거리 특화상권 안내 보행자 및 대중교통 이용객 시선 사로잡는 와이드 래핑', '/images/port/port_15_1.jpg', '["/images/port/port_15_1.jpg"]', 1, 15, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (16, 'did', '뉴스타정형외과의원 버스터미널 대형 조명 와이드 광고', '뉴스타정형외과', '영광종합버스터미널 대합실', '터미널 메인 조명 플래카드', '터미널 이용 군민 및 광역 이동객 대상 척추·관절 특화진료 안내 대형 와이드', '/images/port/port_16_1.jpg', '["/images/port/port_16_1.jpg"]', 1, 16, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (17, 'bus', '닥터스피부과의원 시내버스 후면 고해상도 래핑 광고', '닥터스피부과', '상무지구/수완지구 경유 노선', '시내버스 2대 (후면)', '도심 주요 정체 교차로에서 후방 운전자 시야를 압도하는 프리미엄 피부과 래핑', '/images/port/port_17_1.jpg', '["/images/port/port_17_1.jpg"]', 1, 17, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (18, 'bus', '광주동신대한방병원 전문클리닉 시내버스 차도·인도면 래핑', '동신대한방병원', '광주 전역 간선버스 노선', '시내버스 2개면 풀래핑', '의한 협진 진료 안내 및 척추관절 재활센터 홍보 대형 버스 래핑', '/images/port/port_18_1.jpg', '["/images/port/port_18_1.jpg","/images/port/port_18_2.jpg"]', 1, 18, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (19, 'shelter', '메쓰플랜수학학원 수완·첨단지구 버스승강장 쉘터 광고', '메쓰플랜수학학원', '광주 광산구 학원가 승강장 10개소', '승강장 10곳', '수완/첨단지구 초·중·고 학부모 및 학생 밀집 거점 정류소 집중 노출', '/images/port/port_19_1.jpg', '["/images/port/port_19_1.jpg"]', 1, 19, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (20, 'bus', '밝은안과21병원 시내버스 하차문 시선집중 포스터 광고', '밝은안과21병원', '광주 시내버스 전 노선', '시내버스 하차문 단독면', '하차 직전 모든 승객이 100% 응시하는 골든존 하차문 스팟 광고', '/images/port/port_20_1.jpg', '["/images/port/port_20_1.jpg"]', 1, 20, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (21, 'shelter', '봉선한방병원 봉선동 중심 상권 버스정류장 쉘터 광고', '봉선한방병원', '광주 남구 봉선동 핵심 정류장', '승강장 1개소', '봉선동 메디컬 스트리트 유동인구 타깃 야간 조명 쉘터 광고', '/images/port/port_21_1.jpg', '["/images/port/port_21_1.jpg"]', 1, 21, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (22, 'bus', '광주 북구청 세무과 지방세 납부 홍보 버스 옆면·시트 광고', '광주 북구청', '광주 북구 경유 4개 노선', '시내버스 4대 (인도면+시트)', '성실 납세 홍보 및 스마트 납부 서비스 안내 버스 내외관 동시 집행', '/images/port/port_22_1.jpg', '["/images/port/port_22_1.jpg","/images/port/port_22_2.jpg"]', 1, 22, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (23, 'bus', '북구치매안심센터 치매 조기검진 시내버스 시트커버 광고', '북구치매안심센터', '광주 북구 전역 시내버스', '시내버스 12대 (시트커버)', '만 60세 이상 어르신 무료 치매선별검진 안내 버스 좌석 밀착 홍보', '/images/port/port_23_1.jpg', '["/images/port/port_23_1.jpg"]', 1, 23, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (24, 'bus', '빛고을노인건강타운 셔틀/시내버스 시트커버 안내 광고', '빛고을노인건강타운', '남구 노인타운 경유 노선', '시내버스 15대 (시트커버)', '어르신 여가·문화·체육 종합복지 프로그램 안내 좌석 시트커버 광고', '/images/port/port_24_1.jpg', '["/images/port/port_24_1.jpg"]', 1, 24, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (25, 'bus', '새나래병원 목·어깨 특화진료 시내버스 측면·후면 래핑', '새나래병원', '첨단/상무/충장로 주요 노선', '시내버스 3대 (측면+후면)', '보행자 눈높이의 측면과 차량 운전자 시선의 후면을 동시 공략하는 듀얼 래핑', '/images/port/port_25_1.jpg', '["/images/port/port_25_1.jpg"]', 1, 25, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (26, 'shelter', '세계로병원 관절·척추 전문 버스승강장 와이드 쉘터 광고', '세계로병원', '광주 남구 주요 환승 정류소 3개소', '승강장 3곳', '남구 핵심 거점 버스정류장 야간 LED 조명 결합 고효율 쉘터 광고', '/images/port/port_26_1.jpg', '["/images/port/port_26_1.jpg"]', 1, 26, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (27, 'bus', '세계로병원 전면 풀패키지 시내버스 4면 와이드 래핑', '세계로병원', '광주 중심 간선 3개 노선', '차도면+인도면+후면+하차문', '차도면 3.7m 대형 래핑과 승강장 인도면, 후면, 하차문 4면 풀패키지 시공', '/images/port/port_27_1.jpg', '["/images/port/port_27_1.jpg"]', 1, 27, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (28, 'bus', '셀그램 줄기세포치료 시내버스 하차문 30대 집중 집행', '셀그램 줄기세포', '광주 전역 주요 간선버스', '시내버스 30대 (하차문)', '광주 전역 30개 핵심 노선 하차문 독점 부착으로 폭발적 브랜드 각인 효과', '/images/port/port_28_1.jpg', '["/images/port/port_28_1.jpg"]', 1, 28, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (29, 'bus', '스마트미디어 IT·디지털 교육 시내버스 시트커버 광고', '스마트미디어', '광주 대학가/학원가 경유 노선', '시내버스 24대 (시트커버)', '청년·대학생 타깃 디지털 인재 양성 국비지원 과정 좌석 시트 홍보', '/images/port/port_29_1.jpg', '["/images/port/port_29_1.jpg"]', 1, 29, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (30, 'shelter', '스마트인재개발원 AI·빅데이터 국비과정 승강장 쉘터 광고', '스마트인재개발원', '광주 남구 대학교 인근 승강장 3곳', '승강장 3개소', 'K-디지털 트레이닝 IT 취업 전문과정 청년층 밀집 정류소 타깃 광고', '/images/port/port_30_1.jpg', '["/images/port/port_30_1.jpg","/images/port/port_30_2.jpg"]', 1, 30, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (31, 'bus', '아미아여성의원 프리미엄 여성의학 시내버스 후면 광고', '아미아여성의원', '상무지구/수완지구 경유 노선', '시내버스 2대 (후면)', '후방 대기 차량 운전자 시선에 최적화된 하이엔드 여성클리닉 래핑', '/images/port/port_31_1.jpg', '["/images/port/port_31_1.jpg"]', 1, 31, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (32, 'shelter', '에그탑 카페 광산구 버스정류장 와이드 쉘터 광고', '에그탑 카페', '광주 광산구 주요 승강장 2곳', '승강장 2개소', '디저트&브런치 카페 신규 오픈 및 대표 메뉴 로컬 주민 대상 집중 노출', '/images/port/port_32_1.jpg', '["/images/port/port_32_1.jpg"]', 1, 32, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (33, 'bus', '광주광역시청 군공항 이전 정책홍보 시내버스 측면 래핑', '광주광역시청', '광주 전역 간선 시내버스', '시내버스 인도면 와이드', '광주 미래 발전을 위한 광주 군공항 이전 공공정책 시민 밀착 안내 래핑', '/images/port/port_33_1.jpg', '["/images/port/port_33_1.jpg"]', 1, 33, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (34, 'shelter', '잇올 스파르타 독학재수학원 봉선센터 승강장 쉘터 광고', '잇올 스파르타 봉선센터', '광주 남구 봉선동 학원가 승강장', '봉선동 거점 승강장', '광주 대표 교육특구 봉선동 학원가 수험생 및 학부모 타깃 승강장 광고', '/images/port/port_34_1.jpg', '["/images/port/port_34_1.jpg"]', 1, 34, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (35, 'bus', '광주 친환경 전기·저상버스 하차문 표준 규격 광고', '광주광역시 시내버스', '광주 신형 친환경 저상버스', '신형 저상버스 하차문', '광주 최신 전기·저상버스 하차문 규격 맞춤 고선명 포스터 시공 사례', '/images/port/port_35_1.jpg', '["/images/port/port_35_1.jpg"]', 1, 35, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (36, 'bus', '전남여자상업고등학교 신입생 모집 버스 하차문 광고', '전남여자상업고등학교', '광주 중·고등학교 경유 15개 노선', '시내버스 15대 (하차문)', '특성화고 취업 1위 전남여상 빛나는 비전 중3 여학생 및 학부모 타깃 광고', '/images/port/port_36_1.jpg', '["/images/port/port_36_1.jpg"]', 1, 36, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (37, 'bus', '광주 중독관리통합지원센터 공공안내 시내버스 시트커버', '중독관리통합지원센터', '광주 전역 주요 버스노선', '시내버스 9대 (시트커버)', '알코올·인터넷 중독 예방 및 무료 상담 지원 센터 안내 승객 좌석 광고', '/images/port/port_37_1.jpg', '["/images/port/port_37_1.jpg"]', 1, 37, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (38, 'bus', '여성가족부 청소년근로보호센터 버스 하차문 포스터 광고', '청소년근로보호센터', '광주 주요 대학가/상권 경유 17대', '시내버스 17대 (하차문)', '청소년 아르바이트 권익 보호 및 안심 상담 안내 하차 승객 타깃 부착', '/images/port/port_38_1.jpg', '["/images/port/port_38_1.jpg"]', 1, 38, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (39, 'shelter', '최고안과의원 백내장·시력교정 남구 버스승강장 쉘터', '최고안과의원', '광주 남구 중심 버스정류소 2곳', '승강장 2개소 (시안 리뉴얼)', '남구민 밀집 승강장 LED 조명 와이드 쉘터 시즌별 최신 시안 리뉴얼 집행', '/images/port/port_39_1.jpg', '["/images/port/port_39_1.jpg"]', 1, 39, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (40, 'bus', '킹덤치과의원 임플란트·치아교정 시내버스 측면·후면 래핑', '킹덤치과의원', '광주 중심 번화가 경유 노선', '시내버스 측면 + 후면', '보행자와 후방 차량 운전자 모두를 사로잡는 고화질 치과 브랜드 래핑', '/images/port/port_40_1.jpg', '["/images/port/port_40_1.jpg"]', 1, 40, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (41, 'shelter', '롯데하이마트 첨단점 광산구·북구 버스승강장 쉘터 7개소', '롯데하이마트 첨단점', '광주 광산구 5곳 + 북구 2곳 승강장', '승강장 7개소 와이드', '가전 페스티벌 및 오픈 특별 할인전 북구/광산구 핵심 아파트 밀집 정류소 집행', '/images/port/port_41_1.jpg', '["/images/port/port_41_1.jpg"]', 1, 41, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (42, 'shelter', '롯데하이마트 남구점 버스승강장 와이드 쉘터 광고', '롯데하이마트 남구점', '광주 남구 주요 거점 승강장 3곳', '승강장 3개소', '남구 대표 주거 상권 인근 버스승강장 집중 홍보로 매장 방문 유도', '/images/port/port_42_1.jpg', '["/images/port/port_42_1.jpg"]', 1, 42, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (43, 'shelter', '롯데하이마트 첨단점 버스승강장 17개소 대규모 집중 쉘터', '롯데하이마트 첨단점', '광주 첨단지구 전역 승강장 17개소', '승강장 17곳 대규모 집행', '첨단 1, 2지구 전역 17개 정류소를 완전히 커버하는 와이드 쉘터 광고망 구축', '/images/port/port_43_1.jpg', '["/images/port/port_43_1.jpg"]', 1, 43, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (44, 'shelter', '롯데하이마트 광산점 버스승강장 와이드 쉘터 5개소', '롯데하이마트 광산점', '광주 광산구 중심 상권 승강장 5곳', '승강장 5개소', '수완/하남지구 가전 구매 수요층 타깃 버스승강장 야간 조명 쉘터 광고', '/images/port/port_44_1.jpg', '["/images/port/port_44_1.jpg"]', 1, 44, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (45, 'did', '롯데하이마트 목포종합버스터미널 대형 와이드 조명 광고', '롯데하이마트', '목포종합버스터미널 대합실', '터미널 메인 조명 와이드', '목포터미널 이용 전남 서남권 승객 대상 메가세일 대형 와이드 조명 광고', '/images/port/port_45_1.jpg', '["/images/port/port_45_1.jpg"]', 1, 45, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (46, 'bus', '하이코코이비인후과 시내버스 후면 와이드 래핑 5대', '하이코코 이비인후과', '광주 전역 주요 5개 버스노선', '시내버스 5대 (후면)', '비염·수면클리닉 전문 진료 안내 교차로 후방 운전자 시선 집중 래핑', '/images/port/port_46_1.jpg', '["/images/port/port_46_1.jpg"]', 1, 46, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (47, 'bus', '한사랑병원 척추·관절 종합의료 시내버스 후면 래핑 광고', '한사랑병원', '광주 시내버스 간선 노선', '시내버스 후면', '지역 대표 관절·척추 특화병원 신뢰도 높은 시내버스 후면 와이드 시공', '/images/port/port_47_1.jpg', '["/images/port/port_47_1.jpg"]', 1, 47, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (48, 'bus', '로엘법무법인 봉선27번 시내버스 내부 노선도 광고', '로엘법무법인', '광주 봉선27번 간선 노선', '시내버스 내부 상단 노선도 광고', '봉선27번 시내버스 탑승객을 타깃으로 대표 변호사 1:1 상담 안내 및 브랜드 신뢰도 제고를 위한 내부 노선도 일체형 광고 집행', '/images/port/port_48_1.jpg', '["/images/port/port_48_1.jpg"]', 1, 48, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (49, 'taxi', '퍼플스 결혼정보 광주 개인택시 양면 래핑 광고', '퍼플스 결혼정보', '광주 전역 도심 순환 택시', '택시 좌/우 측면 도어 래핑', '광주 도심 전역을 24시간 운행하는 개인택시 양측 도어에 퍼플스 브랜드 비주얼을 노출하여 핵심 타깃층 인지도 극대화', '/images/port/port_49_1.jpg', '["/images/port/port_49_1.jpg"]', 1, 49, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (50, 'taxi', '미스터초밥 맛집1번지 광주 택시 도어 래핑 광고', '미스터초밥', '광주 주요 상권 및 역사 주변', '택시 좌/우 측면 도어 래핑', '광주 대표 외식 브랜드 미스터초밥의 대표 메뉴 및 슬로건을 택시 측면에 부착하여 도심 이동 차량 및 보행자 집중 노출', '/images/port/port_50_1.jpg', '["/images/port/port_50_1.jpg"]', 1, 50, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (51, 'taxi', '유로진남성의원 광주 택시 측면·후면 패키지 광고', '유로진남성의원', '광주 전역 순환 택시 노선', '택시 측면 도어 + 후면 범퍼 패키지', '광주 도심 순환 개인택시 측면 도어 및 후면 범퍼에 동시 노출하는 패키지 집행으로 후방 차량 및 보행자 도달률 극대화', '/images/port/port_51_1.jpg', '["/images/port/port_51_1.jpg"]', 1, 51, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (52, 'taxi', '한국건강관리협회 광주지부 택시 도어 래핑 광고', '한국건강관리협회', '광주 전역 및 주거 밀집 상권', '택시 좌/우 측면 도어 래핑', '공익 건강검진 캠페인 메시지를 광주 도심 전역을 운행하는 택시 도어에 선명하게 부착하여 정기 검진 수검 독려 및 홍보 집행', '/images/port/port_52_1.jpg', '["/images/port/port_52_1.jpg"]', 1, 52, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (53, 'bus', '닥터스피부과의원 광주-나주 160번 시내버스 후면 광고', '닥터스피부과의원', '광주-나주 160번 광역 간선버스', '시내버스 후면 와이드 래핑', '신세계백화점 광천사거리 위치 닥터스피부과의원의 주요 진료 과목을 신호 대기 차량 및 운전자 시야에 집중 노출하는 시내버스 후면 광고 집행', '/images/port/port_53_1.jpg', '["/images/port/port_53_1.jpg"]', 1, 53, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (54, 'video', '재활의학과 전문의 인터뷰 & 병원 브랜드 필름', '서울하나병원 재활의학과', '광주 상무지구', '4K 시네마틱 인터뷰 & 원내 촬영 (60초)', '의료진의 진솔한 진료 철학과 재활 치료 프로세스를 담아 환자에게 신뢰를 전하는 4K 시네마틱 병원 브랜드 인터뷰 영상 제작', '/images/port/video_01.jpg', '["/images/port/video_01.jpg"]', 1, 54, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (55, 'video', '기업 브랜드 전략 기획 & 홍보영상 사전 프로덕션', '가온엔 크리에이티브', '광주 본사', '스토리보드 기획 & 콘티네이션 사전 제작', '브랜드 아이덴티티와 핵심 타깃 분석을 기반으로 촬영 콘티 및 영상 시나리오를 정밀 기획하는 프로덕션 프리프로덕션', '/images/port/video_02.jpg', '["/images/port/video_02.jpg"]', 1, 55, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (56, 'video', '척추·관절 건강 정보 & 유튜브 의료 가이드 영상', '서울하나병원', '광주 광산구', '유튜브 16:9 교육용 숏·롱폼 콘텐츠', '허리 통증 및 관절 부상 시 일상 속 올바른 초기 대처법과 치료 과정을 전문의가 알기 쉽게 설명하는 의료 가이드 영상 제작', '/images/port/video_03.jpg', '["/images/port/video_03.jpg"]', 1, 56, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (57, 'video', '환자 맞춤 영양 관리 & 입원 치료 케어 다큐멘터리', '메디컬 케어 센터', '광주 첨단지구', '원내 식이요법 다큐멘터리 (30초)', '치료의 핵심 과정인 전문 식이 영양 관리 시스템과 쾌적한 원내 입원 케어 환경을 따뜻한 영상미로 담아낸 홍보 영상', '/images/port/video_04.jpg', '["/images/port/video_04.jpg"]', 1, 57, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (58, 'video', '환자 중심 일상 회복 동행 브랜드 감성 필름', '재활의학센터', '광주 수완지구', '4K 시네마 감성 브랜드 무비', '환자와 보호자의 일상 복귀를 위해 헌신하는 의료진의 세심한 상담과 동행 스토리를 시네마틱 톤앤매너로 제작', '/images/port/video_05.jpg', '["/images/port/video_05.jpg"]', 1, 58, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (59, 'taxi', '각화포스코 단지상가 분양·임대 택배차 래핑 광고', '각화포스코 더샵', '광주 북구 및 인근 신규 택지구역', '택배차량 측면 와이드 래핑', '광주 북구 각화포스코 더샵 단지 내 상가 분양 및 임대 안내를 택배차량 측면에 부착하여 아파트 밀집 지역 및 골목 생활권 집중 노출', '/images/port/port_59_1.jpg', '["/images/port/port_59_1.jpg"]', 1, 59, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (60, 'taxi', '담양 오랑쥬마을 테마파크 눈썰매장 개장 택배차 래핑', '오랑쥬마을 테마파크', '광주-담양 생활권 배송 노선', '택배차량 측면 래핑', '담양 오랑쥬마을 테마파크 겨울 시즌 눈썰매장 개장 소식을 택배 차량에 래핑하여 가족 단위 주거 밀집 지역과 주요 도로 집중 홍보', '/images/port/port_60_1.jpg', '["/images/port/port_60_1.jpg"]', 1, 60, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (61, 'taxi', '원도요양병원 암케어 전문클리닉 택배차량 측면 래핑 광고', '원도요양병원', '광주 북구 및 도심 전역 배송권역', '택배차량 측면 도어·탑 래핑', '체계적인 암케어 및 입원 치료 안내를 도심 골목 구석구석을 운행하는 택배 차량 측면에 부착하여 지역 주민 밀착 홍보 집행', '/images/port/port_61_1.jpg', '["/images/port/port_61_1.jpg"]', 1, 61, 'active', NOW(), NOW());
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES (62, 'taxi', '한국폴리텍대학 광주캠퍼스 직업교육생 모집 택배차 측·후면 광고', '한국폴리텍대학 광주캠퍼스', '광주 전역 택배 배송 권역', '택배차량 측면 + 후면 도어 래핑', '전액 무료 취업 직업교육생 모집 안내를 택배 탑차 측면과 후면 도어에 동시 래핑하여 이동 중인 시민과 후방 운전자에게 전달', '/images/port/port_62_1.jpg', '["/images/port/port_62_1.jpg"]', 1, 62, 'active', NOW(), NOW());


-- 54. 달라온도시락 브랜드 홍보영상
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`)
VALUES (54, 'video', '달라온도시락 브랜드 홍보영상', '달라온도시락', '광주 전역', '10초 브랜드 홍보영상', '정갈한 수제 프리미엄 도시락 제작 과정과 시그니처 메뉴의 신선함을 생생하게 담아낸 브랜드 영상', '/images/port/video_thumb_01.jpg', '["/images/port/video_thumb_01.jpg"]', 1, 54, 'active', NOW(), NOW())
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `client`=VALUES(`client`), `scale`=VALUES(`scale`), `description`=VALUES(`description`), `thumb`=VALUES(`thumb`), `images`=VALUES(`images`), `category`='video';

-- 55. 더다르다김밥 숏폼 릴스/쇼츠 홍보영상
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`)
VALUES (55, 'video', '더다르다김밥 숏폼 릴스/쇼츠 홍보영상', '더다르다김밥', '광주 전역', 'SNS 9:16 모바일 숏폼 영상', 'SNS 맞춤형 9:16 세로형 숏폼 콘텐츠로 고객의 시선을 사로잡는 속도감 있는 트렌디 영상', '/images/port/video_thumb_02.jpg', '["/images/port/video_thumb_02.jpg"]', 1, 55, 'active', NOW(), NOW())
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `client`=VALUES(`client`), `scale`=VALUES(`scale`), `description`=VALUES(`description`), `thumb`=VALUES(`thumb`), `images`=VALUES(`images`), `category`='video';

-- 56. 삼미가 정통 한식 백반 홍보영상
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`)
VALUES (56, 'video', '삼미가 정통 한식 백반 홍보영상', '삼미가', '광주 전역', '외식 브랜드 홍보영상', '깊은 풍미의 전통 한식 상차림과 따뜻한 매장 분위기를 정성스럽게 연출한 외식 브랜드 영상', '/images/port/video_thumb_03.jpg', '["/images/port/video_thumb_03.jpg"]', 1, 56, 'active', NOW(), NOW())
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `client`=VALUES(`client`), `scale`=VALUES(`scale`), `description`=VALUES(`description`), `thumb`=VALUES(`thumb`), `images`=VALUES(`images`), `category`='video';

-- 57. 신우네닭칼국수 시그니처 메뉴 홍보영상
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`)
VALUES (57, 'video', '신우네닭칼국수 시그니처 메뉴 홍보영상', '신우네닭칼국수', '광주 전역', '메뉴 클로즈업 영상', '진한 닭육수와 쫄깃한 면발의 식감을 극대화한 클로즈업 푸드 연출 영상', '/images/port/video_thumb_04.jpg', '["/images/port/video_thumb_04.jpg"]', 1, 57, 'active', NOW(), NOW())
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `client`=VALUES(`client`), `scale`=VALUES(`scale`), `description`=VALUES(`description`), `thumb`=VALUES(`thumb`), `images`=VALUES(`images`), `category`='video';

-- 58. 장어먹자 숯불구이 전문점 홍보영상
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`)
VALUES (58, 'video', '장어먹자 숯불구이 전문점 홍보영상', '장어먹자', '광주 전역', '프리미엄 외식 홍보영상', '숯불 위에서 노릇하게 구워지는 신선한 장어의 먹음직스러운 비주얼을 강조한 보양식 영상', '/images/port/video_thumb_05.jpg', '["/images/port/video_thumb_05.jpg"]', 1, 58, 'active', NOW(), NOW())
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `client`=VALUES(`client`), `scale`=VALUES(`scale`), `description`=VALUES(`description`), `thumb`=VALUES(`thumb`), `images`=VALUES(`images`), `category`='video';

-- 63. 정초밥 프리미엄 일식 스시 홍보영상
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`)
VALUES (63, 'video', '정초밥 프리미엄 일식 스시 홍보영상', '정초밥', '광주 전역', '일식 스시 브랜드 영상', '숙련된 셰프의 정교한 손길과 최고급 식재료의 퀄리티를 섬세하게 담은 프리미엄 홍보영상', '/images/port/video_thumb_06.jpg', '["/images/port/video_thumb_06.jpg"]', 1, 63, 'active', NOW(), NOW())
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `client`=VALUES(`client`), `scale`=VALUES(`scale`), `description`=VALUES(`description`), `thumb`=VALUES(`thumb`), `images`=VALUES(`images`), `category`='video';


-- 54. 달라온도시락 브랜드 홍보영상
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`)
VALUES (54, 'video', '달라온도시락 브랜드 홍보영상', '달라온도시락', '광주 전역', '10초 하이라이트 영상 (대표 프레임 캡쳐본)', '정갈한 수제 프리미엄 도시락 제작 과정 10초 하이라이트 영상 및 대표 스틸컷 캡쳐본', '/images/port/video_thumb_01.jpg', '["/images/port/video_thumb_01.jpg"]', 1, 54, 'active', NOW(), NOW())
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `client`=VALUES(`client`), `scale`=VALUES(`scale`), `description`=VALUES(`description`), `thumb`=VALUES(`thumb`), `images`=VALUES(`images`), `category`='video';

-- 55. 더다르다김밥 숏폼 릴스/쇼츠 홍보영상
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`)
VALUES (55, 'video', '더다르다김밥 숏폼 릴스/쇼츠 홍보영상', '더다르다김밥', '광주 전역', '10초 세로형 숏폼 영상 (대표 프레임 캡쳐본)', 'SNS 맞춤형 9:16 세로형 숏폼 10초 하이라이트 영상 및 대표 스틸컷 캡쳐본', '/images/port/video_thumb_02.jpg', '["/images/port/video_thumb_02.jpg"]', 1, 55, 'active', NOW(), NOW())
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `client`=VALUES(`client`), `scale`=VALUES(`scale`), `description`=VALUES(`description`), `thumb`=VALUES(`thumb`), `images`=VALUES(`images`), `category`='video';

-- 56. 삼미가 정통 한식 백반 홍보영상
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`)
VALUES (56, 'video', '삼미가 정통 한식 백반 홍보영상', '삼미가', '광주 전역', '10초 하이라이트 영상 (대표 프레임 캡쳐본)', '깊은 풍미의 전통 한식 상차림 10초 하이라이트 영상 및 대표 스틸컷 캡쳐본', '/images/port/video_thumb_03.jpg', '["/images/port/video_thumb_03.jpg"]', 1, 56, 'active', NOW(), NOW())
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `client`=VALUES(`client`), `scale`=VALUES(`scale`), `description`=VALUES(`description`), `thumb`=VALUES(`thumb`), `images`=VALUES(`images`), `category`='video';

-- 57. 신우네닭칼국수 시그니처 메뉴 홍보영상
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`)
VALUES (57, 'video', '신우네닭칼국수 시그니처 메뉴 홍보영상', '신우네닭칼국수', '광주 전역', '10초 하이라이트 영상 (대표 프레임 캡쳐본)', '진한 닭육수와 쫄깃한 면발 클로즈업 10초 하이라이트 영상 및 대표 스틸컷 캡쳐본', '/images/port/video_thumb_04.jpg', '["/images/port/video_thumb_04.jpg"]', 1, 57, 'active', NOW(), NOW())
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `client`=VALUES(`client`), `scale`=VALUES(`scale`), `description`=VALUES(`description`), `thumb`=VALUES(`thumb`), `images`=VALUES(`images`), `category`='video';

-- 58. 장어먹자 숯불구이 전문점 홍보영상
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`)
VALUES (58, 'video', '장어먹자 숯불구이 전문점 홍보영상', '장어먹자', '광주 전역', '10초 하이라이트 영상 (대표 프레임 캡쳐본)', '노릇하게 구워지는 신선한 장어구이 10초 하이라이트 영상 및 대표 스틸컷 캡쳐본', '/images/port/video_thumb_05.jpg', '["/images/port/video_thumb_05.jpg"]', 1, 58, 'active', NOW(), NOW())
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `client`=VALUES(`client`), `scale`=VALUES(`scale`), `description`=VALUES(`description`), `thumb`=VALUES(`thumb`), `images`=VALUES(`images`), `category`='video';

-- 63. 정초밥 프리미엄 일식 스시 홍보영상
INSERT INTO `portfolio` (`id`, `category`, `title`, `client`, `location`, `scale`, `description`, `thumb`, `images`, `is_featured`, `sort_order`, `status`, `created_at`, `updated_at`)
VALUES (63, 'video', '정초밥 프리미엄 일식 스시 홍보영상', '정초밥', '광주 전역', '10초 하이라이트 영상 (대표 프레임 캡쳐본)', '셰프의 정교한 손길과 프리미엄 스시 10초 하이라이트 영상 및 대표 스틸컷 캡쳐본', '/images/port/video_thumb_06.jpg', '["/images/port/video_thumb_06.jpg"]', 1, 63, 'active', NOW(), NOW())
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `client`=VALUES(`client`), `scale`=VALUES(`scale`), `description`=VALUES(`description`), `thumb`=VALUES(`thumb`), `images`=VALUES(`images`), `category`='video';
